apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: terraform-cd-example-app-deployment
  namespace: ${namespace}
  labels:
    app: terraform-cd-example-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: terraform-cd-example-app
  template:
    metadata:
      labels:
        app: terraform-cd-example-app
    spec:
      containers:
      - name: terraform-cd-example-app
        image: benjvi/terraform-cd-example-app:${app_version}
        ports:
        - containerPort: 8080
